# Generated by Django 2.0.1 on 2018-01-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(max_length=50)),
                ('student_name', models.CharField(max_length=30)),
                ('subject_id', models.IntegerField(max_length=50)),
                ('subject_name', models.CharField(max_length=30)),
                ('teacher_id', models.IntegerField(max_length=50)),
                ('teacher_name', models.CharField(max_length=30)),
                ('task_name', models.CharField(max_length=50)),
                ('task_grade', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(max_length=50)),
                ('student_name', models.CharField(max_length=30)),
                ('subject_id', models.IntegerField(max_length=50)),
                ('subject_name', models.CharField(max_length=30)),
                ('teacher_id', models.IntegerField(max_length=50)),
                ('teacher_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField(max_length=50)),
                ('subject_name', models.CharField(max_length=30)),
                ('teacher_id', models.IntegerField(max_length=50)),
                ('teacher_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_id', models.IntegerField(max_length=50)),
                ('user_name', models.CharField(max_length=30)),
                ('user_teacher', models.BooleanField(default=False)),
            ],
        ),
    ]
