# Generated by Django 2.0.1 on 2018-01-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_grade',
            name='student_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_grade',
            name='subject_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_grade',
            name='teacher_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_subject',
            name='student_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_subject',
            name='subject_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_subject',
            name='teacher_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='teacher_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
