# Generated by Django 2.0.2 on 2018-02-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180205_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_login',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_password',
            new_name='username',
        ),
    ]
