# Generated by Django 2.0.2 on 2018-02-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('subject_name', models.CharField(max_length=30)),
                ('teacher_id', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=30)),
                ('task_name', models.CharField(max_length=50)),
            ],
        ),
    ]
