# Generated by Django 2.0.2 on 2018-02-13 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180213_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='subject_id',
        ),
    ]
